/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package major;
import javafx.application.Platform;
import major.model.*;
import major.view.GameWindow;
import javafx.application.Application;
import javafx.stage.Stage;
import major.view.SplashScreen;

import java.util.List;

import static javafx.application.Application.launch;


public class App extends Application {



    private SplashScreen splashScreen = new SplashScreen();
    private int loadTime = 15;

    private CMCAPI input;
    private TwilioAPI output;


    public static void main(String[] args) {
        launch(args);
    }


    public void start(Stage primaryStage){





        Stage splash = splashScreen.getStage();
        splash.show();



        Thread load = new Thread(()->{
            for (int a =0 ; a<loadTime; a++){
                try {

                    Thread.sleep(1000);

                } catch (InterruptedException e) {
                    throw new RuntimeException(e);
                }
                splashScreen.increase(a);

            }
            Platform.runLater(new Runnable() {
                @Override
                public void run() {
                    splash.close();



                    Parameters params = getParameters();
                    List<String> list = params.getRaw();
                    System.out.println(list.size());
                    for(String each : list){
                        System.out.println(each);
                    }

                    String in = list.get(0);
                    String out = list.get(1);



                    if (in.equals("online")){

                        HTTP http = new HTTP();
                        input = new CMCInputOnline();
                        input.injectHttp(http);
                        input.injectSQL(new SQL());
                        if(out.equals("online")){
                            output = new TwilioOnline();
                            output.injectHttp(http);

                        }else{
                            output = new TwilioOffline();
                        }

                    }else{
                        HTTP http = new HTTP();
                        input = new CMCInputOffline();
                        if(out.equals("online")){
                            output = new TwilioOnline();
                            output.injectHttp(http);

                        }else{
                            output = new TwilioOffline();
                        }

                    }



                    Controller control = new Controller(input, output);


                    GameWindow view = new GameWindow(control);
                    primaryStage.setWidth(900);
                    primaryStage.setHeight(900);
                    primaryStage.setScene(view.getScene());
                    primaryStage.setTitle("Coin Market Cap");
                    primaryStage.show();
                }
            });
        });
        load.start();







    }
}
